# Generated by Django 5.2.3 on 2025-07-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ownuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_P59',
        ),
        migrations.RemoveField(
            model_name='ownuser',
            name='active',
        ),
        migrations.AddField(
            model_name='ownuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownuser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
