# Generated by Django 5.2.3 on 2025-07-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_product_p59_remove_ownuser_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
